package com.zzz.androidvocab.core.designsystem

import androidx.compose.ui.graphics.Color

object VocabColors {
    val LightBackground = Color(0xFFF5F5F7)
    val DarkBackground = Color(0xFF0B0B0F)
    val LightSurface = Color(0xFFFFFFFF)
    val DarkSurface = Color(0xFF17171C)
    val LightSurfaceElevated = Color(0xFFFFFFFF)
    val DarkSurfaceElevated = Color(0xFF1F1F26)
    val LightSurfaceMuted = Color(0xFFE9EBF0)
    val DarkSurfaceMuted = Color(0xFF24242C)
    val LightOutline = Color(0xFFD8DCE5)
    val DarkOutline = Color(0xFF31313A)
    val Primary = Color(0xFF2563EB)
    val PrimarySoft = Color(0xFFDCE7FF)
    val PrimaryDarkSoft = Color(0xFF18306A)
    val Success = Color(0xFF2F8F5B)
    val SuccessSoft = Color(0xFFDCEEDA)
    val Danger = Color(0xFFE14B4B)
    val DangerSoft = Color(0xFFF9DFDE)
    val Warning = Color(0xFFC9861A)
    val WarningSoft = Color(0xFFF6E5BE)
    val TextPrimaryLight = Color(0xFF1C1C1E)
    val TextPrimaryDark = Color(0xFFF5F5F7)
    val TextSecondaryLight = Color(0xFF63636C)
    val TextSecondaryDark = Color(0xFFA9ADBA)
    val HeroBackground = Color(0xFFF1F4FA)
    val HeroBackgroundDark = Color(0xFF141722)
    val HeroBorder = Color(0xFFD6DCE8)
    val HeroBorderDark = Color(0xFF2A3140)
    val ErrorCardBackground = Color(0xFFFFEEEF)
    val ErrorCardBackgroundDark = Color(0xFF2A1417)
    val HeatmapLevel1 = Color(0xFFE3E7EE)
    val HeatmapLevel2 = Color(0xFFC9D4E2)
    val HeatmapLevel3 = Color(0xFF91BCA3)
    val HeatmapLevel4 = Color(0xFF2F8F5B)
    val HeatmapLevel1Dark = Color(0xFF22252B)
    val HeatmapLevel2Dark = Color(0xFF27343F)
    val HeatmapLevel3Dark = Color(0xFF315143)
    val HeatmapLevel4Dark = Color(0xFF5CA56E)
}
